### ISSUE TITLE
how to calculate a_weighting:coeffs？

### ISSUE THREAD

**Issue by zuowanbushiwo** [kwarc93/spl-meter#1]
Hi @kwarc93 
     about   https://github.com/kwarc93/spl-meter/blob/b386d9f457d50b5e3468fa92192d9fb292fa0f20/app/model/weighting_filter.hpp#L38  and  https://github.com/kwarc93/spl-meter/blob/b386d9f457d50b5e3468fa92192d9fb292fa0f20/app/model/weighting_filter.hpp#L52 
How to get these two parameters？

Thanks
best

**Comment by kwarc93** [comment]
Hi @zuowanbushiwo, look at the "scripts" directory, there is a matlab/octave script that generates them.

**Comment by zuowanbushiwo** [comment]
Hi @kwarc93 
Thanks a lot.  Did you find a C/C++ implementation? Because the sampling rate of my current system is set dynamically.
And is this way suitable for mobile phones and windows PC , why?
I see a lot of  Implementation of software  decibel meters or sound meters  like this:
 ```
double amplitude = mRecorder.getMaxAmplitude(); //Returns the maximum absolute amplitude that was sampled since the last call to this method
 double dbl = convertdDb(amplitude);

 public double convertdDb(double amplitude) {
        // Cellphones can catch up to 90 db + -
        // getMaxAmplitude returns a value between 0-32767 (in most phones). that means that if the maximum db is 90, the pressure
        // at the microphone is 0.6325 Pascal.
        // it does a comparison with the previous value of getMaxAmplitude.
        // we need to divide maxAmplitude with (32767/0.6325)
        //51805.5336 or if 100db so 46676.6381
        double EMA_FILTER = 0.6;
        SharedPreferences sp = this.getSharedPreferences("device-base", MODE_PRIVATE);
        double amp = (double) sp.getFloat("amplitude", 0);
        double mEMAValue = EMA_FILTER * amplitude + (1.0 - EMA_FILTER) * mEMA;
        Log.d("db", Double.toString(amp));
        //Assuming that the minimum reference pressure is 0.000085 Pascal (on most phones) is equal to 0 db
        // samsung S9 0.000028251
        return 20 * (float) Math.log10((mEMAValue/51805.5336)/ 0.000028251);
    }
```
Looking forward to your reply
best wishes

**Comment by zuowanbushiwo** [comment]
Hi @kwarc93  
I found a way to calculate SPL in frequency domain [here](http://davidegironi.blogspot.com/2014/02/a-simple-sound-pressure-level-meter-spl.html#.YrqYanZBw2w):
To compute SPL measurements, the meters loop is:
 1.   collects N samples
 2.   do FFT for the N samples collected, the signal is now transformed in the frequency domain
 3.   apply A-weighting (in freq domain)
 4.   get magnitude of the signal
 5.  get RMS value of the signal
 6.  apply a time-weight filter to RMS value
 7.  compute the SPL using the RMS value
 8.  output data

Is this very different from your method?
thanks！

**Comment by kwarc93** [comment]
Hi @zuowanbushiwo 
I don't have "C/C++ version" of this script. In your case, where fs is set dynamically, you can try prepare a set of different coeffs for given fs and swap them at runtime.

Regarding this "convertdDb(amplitude)" function: I think it is not a proper way of calculating dB because it does a lot of assumptions and does not use the RMS value of a signal (only peak value) and the sensitivity of a microphone is not known.

The last algorithm You provided is almost the same as mine. The only diffrence is that I'm doing filtering in the time domain instead of frequency domain. To correctly calculate the dB SPL you must know the sensitivity of your microphone.

Regards

**Comment by zuowanbushiwo** [comment]
@kwarc93 
  Thanks for your advice

` To correctly calculate the dB SPL you must know the sensitivity of your microphone. `

 Is there any convenient way to simply determine this parameter? Can it only be determined by hardware parameters? 
 I want to port it to other platforms (after modifying some source code, mainly Android and win), can I use a real decibel meter to calibrate this parameter?  In addition to a real decibel meter (currently I don't have this device at hand), there are many software decibel meter software in the ios app store, are these ok?

Looking forward to your reply
best wishes

**Comment by zuowanbushiwo** [comment]
Hi @kwarc93 
Today I installed matlab(R2018a) , and run the script  `weighting_filter.m` ，but can't get ` a_weighting::coeffs`, why?

<img width="423" alt="image" src="https://user-images.githubusercontent.com/3354428/176382856-401d098a-95ad-44e3-9b9a-17c2497f9ef4.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/3354428/176382910-f7464d04-5d30-4683-8b4e-48c751037fef.png">

**Comment by zuowanbushiwo** [comment]
Just changed the way of annotations
```
diff --git a/scripts/weighting_filter.m b/scripts/weighting_filter.m
index 959acbe..bbed105 100644
--- a/scripts/weighting_filter.m
+++ b/scripts/weighting_filter.m
@@ -1,12 +1,12 @@
-# Script converts analog filter transfer function to digital domain
-# and calculates coefficients for biquad cascade IIR digital filter.
+%# Script converts analog filter transfer function to digital domain
+%# and calculates coefficients for biquad cascade IIR digital filter.

 clear all
 close all

 Fs = 40000;

-# Definition of analog A-weighting filter according to IEC/CD 1672.
+%# Definition of analog A-weighting filter according to IEC/CD 1672.
 f1 = 20.598997;
 f2 = 107.65265;
 f3 = 737.86223;
@@ -17,7 +17,7 @@ num = [(2*pi*f4)^2*(10^(a1000/20)) 0 0 0 0];
 den = conv([1 +4*pi*f4 (2*pi*f4)^2],[1 +4*pi*f1 (2*pi*f1)^2]);
 den = conv(conv(den,[1 2*pi*f3]),[1 2*pi*f2]);

-# Definition of analog C-weighting filter according to IEC/CD 1672.
+%# Definition of analog C-weighting filter according to IEC/CD 1672.
 %f1 = 20.598997;
 %f4 = 12194.217;
 %c1000 = 0.0619;
@@ -25,21 +25,21 @@ den = conv(conv(den,[1 2*pi*f3]),[1 2*pi*f2]);
 %num = [(2*pi*f4)^2*(10^(c1000/20)) 0 0];
 %den = conv([1 +4*pi*f4 (2*pi*f4)^2],[1 +4*pi*f1 (2*pi*f1)^2]);

-# Use bilinear to transform it to a discrete-time IIR filter.
+%# Use bilinear to transform it to a discrete-time IIR filter.
 [numz,denz] = bilinear(num,den,1/Fs);

-# Visualize filters frequency response
+%# Visualize filters frequency response
 figure
 fmin = 10;
 fmax = Fs + 0.1*Fs;
 omega = logspace(log10(2*pi*fmin), log10(2*pi*fmax));

-# Analog filter
+%# Analog filter
 hs = freqs(num,den,omega);
 semilogx(omega/(2*pi), 20*log10(abs(hs)), 'color', 'b', 'linewidth', 2);
 grid on; hold on;

-# Digital filter
+%# Digital filter
 n = ceil(Fs/fmin);
 [hz,wz] = freqz(numz,denz,n);
 semilogx(wz*Fs/(2*pi), 20*log10(abs(hz)), 'color', 'r', 'linewidth', 2, 'linestyle', '--');
@@ -49,6 +49,6 @@ legend('analog', 'digital')
 xlabel('Frequency (Hz)')
 ylabel('Magnitude (dB)')

-# Get digital filter coefficients (for biquad cascade IIR)
+%# Get digital filter coefficients (for biquad cascade IIR)
 sos = tf2sos(numz, denz)
```

**Comment by kwarc93** [comment]
Actually I used Octave instead of Matlab and thus there may be some differences between them. I assume that "bilinear()" function in Matlab takes "Fs" (not "1/Fs") as a last argument.

Regarding mic sensitivity - you can find it in the datasheet. If you dont know the sensitivity, I think you need some reference meter to calibrate. In terms of Android apps - I dont know ;)

**Comment by zuowanbushiwo** [comment]
@kwarc93 
Thanks a lot,  After changing that parameter, the result seems to be normal
<img width="424" alt="image" src="https://user-images.githubusercontent.com/3354428/176407772-72ac7a66-f036-4395-845a-83e0ec675caf.png">

 but The final dimension of sos is also wrong, Matlab sos is `3X6 `,  `a_weighting::coeffs` is `3X5` ? 
matlab out ：
```
sos =
    0.2815    0.5630    0.2815    1.0000   -1.8737    0.8755
    1.0000   -2.0001    1.0001    1.0000   -1.9935    0.9935
    1.0000   -1.9999    0.9999    1.0000   -0.0432    0.0005
```
```
static constexpr float coeffs[5 * iir_stages] = {2.8148e-01, -5.6291e-01, 2.8144e-01, 4.3181e-02, -4.6615e-04,
                                                 1.0000e+00, -2.0001e+00, 1.0001e+00, 1.9935e+00, -9.9355e-01,
                                                 1.0000e+00,  2.0000e+00, 1.0000e+00, 1.8737e+00, -8.7551e-01};

```
Compare these two parameters:
(1) `a_weighting::coeffs` is missing the matlab‘s 4th column, this column is all 1
(2)` a_weighting::coeffs` column 4 column 5, compared to column 5 column 6 of matlab, there is a vertical flip

is that so?
Looking forward to your reply
best wishes

**Comment by kwarc93** [comment]
I assume that the coeffs from script are correct (or this is another difference between Matlab and Octave). I just had to arrange them according to the filtering method I used:
https://arm-software.github.io/CMSIS_5/DSP/html/group__BiquadCascadeDF1.html

**Comment by zuowanbushiwo** [comment]
Hi @kwarc93 
Thanks，You're so friendly and one last question：

When I set FS = 16000, the output of matlab is:
```
0.531489829823557	    1.06297965964711	0.531489829823555	1	0.821563817981107	0.168741776753923
1	                   -2.00012859785797	1.00012860612864	1	-1.70550963370390	0.715987575344363
1	                   -1.99987140214203	0.999871410408779	1	-1.98388675726937	0.983951666417237
```
then change to  a_weighting::coeffs  is

```
0.531489829823557	    1.06297965964711	0.531489829823555   -1.98388675726937	0.983951666417237
1	                   -2.00012859785797	1.00012860612864    -1.70550963370390	0.715987575344363
1	                   -1.99987140214203	0.999871410408779    0.821563817981107	0.168741776753923
```
Is it right?  If not, what is the correct output?
Looking forward to your reply
best wishes

**Comment by kwarc93** [comment]
When I set Fs=16000, the Octave give me:
```
sos =

   0.53149  -1.06290   0.53141   1.00000   0.82156   0.16874
   1.00000  -2.00014   1.00014   1.00000  -1.98389   0.98395
   1.00000   2.00000   1.00000   1.00000  -1.70551   0.71599
```

which looks like that some coeffs are placed differently in the matrix in comparison to Matlab output. I don't know why, can't help. The only way to know is to read MATLAB documentation and verify the script ;) 
Good luck

**Comment by zuowanbushiwo** [comment]
@kwarc93 
Sorry to bother you again, but there are a lot of things I don't understand now.
Today I installed Octave on my windows 10, the version information of Octave is as follows:
```
GNU Octave, version 7.1.0
Copyright (C) 1993-2022 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-w64-mingw32".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.
```
then install  `Octave  signal-1.4.2 ` package

(1)  run original scripts(Fs = 40000)  , my Octave   output :
<img width="512" alt="image" src="https://user-images.githubusercontent.com/3354428/176572517-7a404640-59a2-41f9-b506-f11dbcf769ac.png">

The output of this result is different from that of my matlab, but it should be the same as the output of your Octave (because it's the same as `a_weighting::coeffs`，except for columns 4 and 5 where the sign is reversed)。

(2) when set Fs=16000， my Octave  output：
<img width="374" alt="image" src="https://user-images.githubusercontent.com/3354428/176573154-be28b266-0eef-40ee-9bb9-b63ac26696b1.png">

the output of this result is different from that of your Octave，It's so strange，why?  but it is  the same as the output of my matlab，It's also strange，why? 


Looking forward to your reply
best wishes

**Comment by zuowanbushiwo** [comment]
Thanks！
